#!/usr/bin/env python3
# ============================================================
# server.py — Obscura Clips Web UI Server
# Serves the beautiful UI and streams pipeline progress
# via WebSocket in real-time.
# ============================================================

import asyncio
import os
import re
import sys
import time
import uuid
import webbrowser
import threading
import json
import logging
from pathlib import Path

import uvicorn
from fastapi import FastAPI, WebSocket, UploadFile, File, Query
from fastapi.responses import HTMLResponse, FileResponse, JSONResponse

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("server")

# ─── Paths ──────────────────────────────────────────────────
BASE_DIR   = Path(__file__).parent
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

UPLOAD_DIR = BASE_DIR / "temp" / "uploads"
OUTPUT_DIR = BASE_DIR / "output"
UI_FILE    = BASE_DIR / "ui" / "index.html"

UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


app  = FastAPI(title="Obscura Clips")
jobs: dict = {}   # job_id → {"path": str, "filename": str, "start_time": float}

# --- State for reconnecting websockets ---
job_events: dict = {}       # job_id -> list of all JSON events generated by the process
job_done: dict = {}         # job_id -> boolean indicating if process has finished


# ─── Routes ─────────────────────────────────────────────────

@app.get("/api/check-nvidia-key")
async def check_nvidia_key():
    load_dotenv(BASE_DIR / ".env", override=True)
    key = os.environ.get("NVIDIA_API_KEY", "")
    is_set = len(key) > 0
    masked_key = ""
    if is_set:
        masked_key = key[:6] + "..." + key[-4:] if len(key) > 10 else "..."
    return {"is_set": is_set, "masked_key": masked_key}


@app.post("/api/save-nvidia-key")
async def save_nvidia_key(payload: dict):
    key = payload.get("key", "").strip()
    env_path = BASE_DIR / ".env"
    
    lines = []
    key_found = False
    if env_path.exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip().startswith("NVIDIA_API_KEY="):
                    lines.append(f"NVIDIA_API_KEY={key}\n")
                    key_found = True
                else:
                    lines.append(line)
    if not key_found:
        lines.append(f"NVIDIA_API_KEY={key}\n")
    
    with open(env_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
        
    os.environ["NVIDIA_API_KEY"] = key
    return {"success": True, "message": "NVIDIA API Key saved permanently to backend."}


@app.get("/", response_class=HTMLResponse)
async def index():
    return UI_FILE.read_text(encoding="utf-8")


@app.post("/upload")
async def upload_video(file: UploadFile = File(...)):
    """Accept a video upload and return a job_id."""
    job_id = str(uuid.uuid4())[:8]
    suffix = Path(file.filename).suffix or ".mp4"
    save_path = UPLOAD_DIR / f"job_{job_id}{suffix}"

    # Stream-write in 4 MB chunks to handle large files
    with open(save_path, "wb") as f:
        while True:
            chunk = await file.read(4 * 1024 * 1024)
            if not chunk:
                break
            f.write(chunk)

    jobs[job_id] = {
        "path":     str(save_path),
        "filename": file.filename,
        "start_time": time.time()
    }
    return {"job_id": job_id, "filename": file.filename}
@app.get("/api/music/tracks")
async def get_music_tracks():
    """Retrieve available local and curated background tracks."""
    from modules.bg_music import list_available_tracks
    try:
        return list_available_tracks()
    except Exception as e:
        logger.error(f"Error listing music tracks: {e}")
        return []



async def _run_process(job_id: str, cmd: list, start_time: float):
    try:
        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=str(BASE_DIR),
            env={**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"}
        )
        jobs[job_id]["process"] = process

        while True:
            line_bytes = await process.stdout.readline()
            if not line_bytes:
                break
            text = line_bytes.decode("utf-8", errors="replace").rstrip()
            if not text.strip():
                continue

            event = _parse_log_line(text)
            event["raw"] = text
            job_events[job_id].append(event)

        await process.wait()
        success = process.returncode == 0
        if success:
            job_dir = OUTPUT_DIR / job_id
            job_dir.mkdir(parents=True, exist_ok=True)
            meta = {
                "job_id": job_id,
                "filename": jobs[job_id]["filename"],
                "created": time.time()
            }
            with open(job_dir / "metadata.json", "w", encoding="utf-8") as f:
                json.dump(meta, f)

        clips = _list_clips(job_id=job_id, newer_than=start_time - 5)
        job_events[job_id].append({
            "type": "done",
            "success": success,
            "clips": clips
        })
    except Exception as e:
        job_events[job_id].append({"type": "error", "message": str(e)})
    finally:
        job_done[job_id] = True

job_configs = {}

@app.post("/config/{job_id}")
async def set_job_config(job_id: str, request: Request):
    job_configs[job_id] = await request.json()
    return {"status": "ok"}

@app.websocket("/ws/{job_id}")
async def run_pipeline_ws(
    websocket: WebSocket,
    job_id:    str
):
    await websocket.accept()
    
    config = job_configs.get(job_id, {})
    model = config.get("model", "small")
    max_clips = int(config.get("max_clips", 10))
    language = config.get("language", "")
    music = config.get("music", "none")
    caption_style = config.get("caption_style", "kinetic_slide")
    font_preset = config.get("font_preset", "Montserrat-Black")
    font_name = config.get("font_name", "")
    font_size = int(config.get("font_size", 48))
    primary_color = config.get("primary_color", "#FFFFFF")
    outline_color = config.get("outline_color", "#000000")
    no_title = config.get("no_title", False)
    broll = config.get("broll", False)
    pexels_key = config.get("pexels_key", "")
    force_restart = config.get("force_restart", False)

    if job_id not in jobs:
        await websocket.send_json({"type": "error", "message": "Job not found."})
        await websocket.close()
        return

    job = jobs[job_id]
    start_time = job["start_time"]
    
    if force_restart or job_id not in job_events:
        job_events[job_id] = []
        job_done[job_id] = False
        
        job_events[job_id].append({"type": "start", "filename": job["filename"]})

        if music == "off": music = "none"
        job_dir = OUTPUT_DIR / job_id
        job_dir.mkdir(parents=True, exist_ok=True)
        
        python_exe = str(BASE_DIR / "venv" / "Scripts" / "python.exe")
        if not Path(python_exe).exists():
            python_exe = str(BASE_DIR / "venv" / "bin" / "python")
            if not Path(python_exe).exists():
                python_exe = sys.executable

        cmd = [
            python_exe,
            str(BASE_DIR / "local_clipping_pipeline.py"),
            "--input", job["path"],
            "--output-dir", str(job_dir),
            "--model", model,
            "--max-clips", str(max_clips),
            "--music", music,
            "--caption-style", caption_style,
            "--font-preset", font_preset,
            "--font-name", font_name,
            "--font-size", str(font_size),
            "--primary-color", primary_color,
            "--outline-color", outline_color,
        ]
        if no_title: cmd += ["--no-title"]
        if broll and pexels_key.strip(): cmd += ["--broll", "--pexels-key", pexels_key.strip()]
        if language.strip(): cmd += ["--language", language.strip()]

        asyncio.create_task(_run_process(job_id, cmd, start_time))

    try:
        last_index = 0
        while True:
            if last_index < len(job_events[job_id]):
                event = job_events[job_id][last_index]
                await websocket.send_json(event)
                last_index += 1
                if event.get("type") in ("done", "error"):
                    break
            elif job_done[job_id]:
                break
            else:
                await asyncio.sleep(0.5)
    except Exception as e:
        logger.error(f"WebSocket error in run_pipeline_ws for job {job_id}: {e}")
    finally:
        try:
            await websocket.close()
        except Exception:
            pass


# ─── Helpers ────────────────────────────────────────────────

def _parse_log_line(text: str) -> dict:
    """Convert a raw pipeline log line into a structured UI event."""

    # Main stage: "═══ STAGE 2/6 ─ ASR Transcription (CPU INT8) ═══"
    m = re.search(r"STAGE\s+(\d+)/6[^─\-]*[\-─]\s*(.+?)(?:\s*[═=]+\s*$|\s*$)", text)
    if m:
        return {"type": "stage", "stage": int(m.group(1)), "label": m.group(2).strip()}

    # Clip start: "═══ CLIP 1/5 ══"
    m = re.search(r"CLIP\s+(\d+)/(\d+)", text)
    if m:
        return {"type": "clip_start", "clip_num": int(m.group(1)), "total": int(m.group(2))}

    # Sub-stage: "[4/6] Face Tracking"
    m = re.search(r"\[(\d+)/6\]\s+(.+)", text)
    if m:
        return {"type": "substage", "substage": int(m.group(1)), "label": m.group(2).strip()}

    # Clip ready: "✅ Done → output/clip_01_..."
    m = re.search(r"Done.*?(?:→|->)\s*(output[/\\].+?\.mp4)", text, re.IGNORECASE)
    if m:
        return {"type": "clip_ready", "path": m.group(1)}

    # Errors / warnings
    low = text.lower()
    if "error" in low or "failed" in low or "traceback" in low:
        return {"type": "warning"}

    return {"type": "log"}


def _list_clips(job_id: str = None, newer_than: float = 0) -> list:
    clips = []
    if not OUTPUT_DIR.exists():
        return clips
        
    dirs_to_search = [OUTPUT_DIR / job_id] if job_id else [d for d in OUTPUT_DIR.iterdir() if d.is_dir()]

    for target_dir in dirs_to_search:
        # Read clips metadata if available to merge LLM analysis
        metadata_by_name = {}
        if target_dir.exists():
            metadata_file = target_dir / "clips_metadata.json"
            if metadata_file.exists():
                try:
                    import json
                    with open(metadata_file, "r", encoding="utf-8") as f:
                        meta_list = json.load(f)
                    for idx, item in enumerate(meta_list):
                        clip_num = idx + 1
                        title = item.get("title", f"clip_{clip_num:03d}")
                        safe_title = "".join(c if c.isalnum() or c in " _-" else "" for c in title)
                        safe_title = safe_title.strip().replace(" ", "_")[:40]
                        clip_filename = f"clip_{clip_num:02d}_{safe_title}.mp4"
                        metadata_by_name[clip_filename] = item
                except Exception as e:
                    logger.error(f"Failed to read clips metadata: {e}")

        if target_dir.exists():
            for f in target_dir.glob("*.mp4"):
                stat = f.stat()
                if stat.st_mtime < newer_than:
                    continue
                url_path = f"/output/{target_dir.name}/{f.name}"
                
                # Find matching metadata from clips_metadata.json
                clip_meta = metadata_by_name.get(f.name, {})
                
                clips.append({
                    "filename": f.name,
                    "size_mb":  round(stat.st_size / 1024 / 1024, 1),
                    "url":      url_path,
                    "modified": stat.st_mtime,
                    "title":    clip_meta.get("title", f.name),
                    "social_caption": clip_meta.get("social_caption", ""),
                    "reason":   clip_meta.get("reason", ""),
                    "hook_score": clip_meta.get("hook_score", "?"),
                    "viral_rating": clip_meta.get("viral_rating", None),
                    "retention_score": clip_meta.get("retention_score", None),
                    "viral_analysis": clip_meta.get("viral_analysis", ""),
                    "broll_cues": clip_meta.get("broll_cues", [])
                })
    return sorted(clips, key=lambda c: c["modified"], reverse=True)


# ─── yt-dlp Download Endpoints ─────────────────────────────

@app.post("/prepare-download")
async def prepare_download():
    """Reserve a job_id for an incoming yt-dlp download."""
    job_id = str(uuid.uuid4())[:8]
    return {"job_id": job_id}


@app.websocket("/ws-ytdl/{job_id}")
async def download_url_ws(
    websocket: WebSocket,
    job_id:    str,
    url:       str = Query(...)
):
    """
    Download a video from a URL using yt-dlp and stream progress
    to the browser. On completion, registers the job so the
    pipeline WebSocket can use it directly.
    """
    await websocket.accept()

    # Use the venv Python so all packages are available (cross-platform check)
    python_exe = str(BASE_DIR / "venv" / "Scripts" / "python.exe")
    if not Path(python_exe).exists():
        python_exe = str(BASE_DIR / "venv" / "bin" / "python")
        if not Path(python_exe).exists():
            python_exe = sys.executable

    save_path = UPLOAD_DIR / f"job_{job_id}.mp4"

    cmd = [
        python_exe, "-m", "yt_dlp",
        "--format",
        "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "--merge-output-format", "mp4",
        "--output",             str(save_path),
        "--newline",            # one progress line per line — easy to parse
        "--no-playlist",
        "--no-part",            # no .part files
        url
    ]

    await websocket.send_json({"type": "ytdl_start", "url": url})

    try:
        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            env={**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"}
        )

        video_title = "downloaded_video"

        while True:
            line_bytes = await process.stdout.readline()
            if not line_bytes:
                break
            text = line_bytes.decode("utf-8", errors="replace").rstrip()
            if not text.strip():
                continue

            # Capture the video title from the destination line
            m = re.search(r"\[download\] Destination: (.+)", text)
            if m:
                video_title = Path(m.group(1)).stem

            # Parse download progress:
            # [download]  45.2% of 234.56MiB at 2.34MiB/s ETA 00:43
            m = re.search(
                r"\[download\]\s+([\d.]+)%\s+of\s+([~\d.]+\w+)\s+at\s+([\d.]+\w+/s)\s+ETA\s+(\S+)",
                text
            )
            if m:
                await websocket.send_json({
                    "type":    "ytdl_progress",
                    "percent": float(m.group(1)),
                    "size":    m.group(2),
                    "speed":   m.group(3),
                    "eta":     m.group(4),
                })
                continue

            # Forward other lines as log
            await websocket.send_json({"type": "ytdl_log", "raw": text})

        await process.wait()

        if process.returncode == 0 and save_path.exists():
            # Register job so the pipeline WS can use it directly
            jobs[job_id] = {
                "path":       str(save_path),
                "filename":   video_title + ".mp4",
                "start_time": time.time(),
            }
            await websocket.send_json({
                "type":     "ytdl_done",
                "job_id":   job_id,
                "filename": video_title + ".mp4",
                "size_mb":  round(save_path.stat().st_size / 1024 / 1024, 1),
            })
        else:
            await websocket.send_json({
                "type":    "error",
                "message": "Download failed. Check the URL or try a different quality."
            })

    except Exception as e:
        try:
            await websocket.send_json({"type": "error", "message": str(e)})
        except Exception:
            pass
    finally:
        try:
            await websocket.close()
        except Exception:
            pass


@app.get("/uploads")
async def list_uploads():
    uploads = []
    if UPLOAD_DIR.exists():
        for f in UPLOAD_DIR.glob("job_*.mp4"):
            m = re.match(r"job_([a-f0-9]{8})\.mp4", f.name)
            if m:
                jid = m.group(1)
                stat = f.stat()
                if jid not in jobs:
                    jobs[jid] = {
                        "path": str(f),
                        "filename": f.name,
                        "start_time": stat.st_mtime
                    }
                uploads.append({
                    "job_id": jid,
                    "filename": jobs[jid]["filename"],
                    "size_mb": round(stat.st_size / 1024 / 1024, 1),
                    "created": stat.st_mtime
                })
    return {"uploads": sorted(uploads, key=lambda x: x["created"], reverse=True)}


@app.get("/clips")
async def list_clips_endpoint():
    return {"clips": _list_clips()}


@app.get("/history")
async def get_history():
    history = []
    if OUTPUT_DIR.exists():
        for d in OUTPUT_DIR.iterdir():
            if d.is_dir() and (d / "metadata.json").exists():
                try:
                    with open(d / "metadata.json", "r", encoding="utf-8") as f:
                        meta = json.load(f)
                    
                    # Double check if there are actual clips in it
                    clips = list(d.glob("*.mp4"))
                    if clips:
                        meta["clip_count"] = len(clips)
                        history.append(meta)
                except Exception as e:
                    logger.error(f"Error reading metadata for {d.name}: {e}")
    return {"history": sorted(history, key=lambda x: x.get("created", 0), reverse=True)}


@app.get("/history/{job_id}/clips")
async def get_history_clips(job_id: str):
    return {"clips": _list_clips(job_id=job_id)}


@app.get("/output/{job_id}/{filename}")
async def serve_job_output(job_id: str, filename: str):
    path = OUTPUT_DIR / job_id / filename
    if not path.exists():
        return JSONResponse({"error": "not found"}, status_code=404)
    return FileResponse(str(path), media_type="video/mp4")


@app.get("/output/{filename}")
async def serve_output(filename: str):
    path = OUTPUT_DIR / filename
    if not path.exists():
        return JSONResponse({"error": "not found"}, status_code=404)
    return FileResponse(str(path), media_type="video/mp4")


# ─── Entry Point ─────────────────────────────────────────────

def _open_browser():
    time.sleep(1.5)
    webbrowser.open("http://localhost:7842")


if __name__ == "__main__":
    threading.Thread(target=_open_browser, daemon=True).start()
    print("\n  *  Obscura Clips - UI server starting")
    print("  -> http://localhost:7842")
    print("  -> Press Ctrl+C to stop\n")
    uvicorn.run(app, host="127.0.0.1", port=7842, log_level="warning")
